image: Visual Studio 2017

environment:
  VS_VERSION: vs2017
  QTDIR: C:\Qt\5.12\msvc2017_64
  PLATFORM: msvc2017_64

platform:
  - x64

install:
  - C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat x64
  - set VC_VARSALL=amd64
  - set PATH=%PATH%;%QTDIR%\bin
  - git submodule update --init --recursive
build_script:
  - call %VC_DIR% %VC_VARSALL% || exit /B 1
  - cmake -B build
  - cmake --build build
  # check that it runs fine
  - build/WololoKingdoms.exe --help
