image: Visual Studio 2017

environment:
  VS_VERSION: vs2017
  QTDIR: C:\Qt\5.12\msvc2017
  PLATFORM: msvc2017

platform:
  - x86

install:
  - set PATH=%PATH%;%QTDIR%\bin
  - git submodule update --init --recursive
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat" || exit /B 1
  - cmake -B build -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build
  - 7z a build\WololoKingdoms.zip build\bin

artifacts:
  - path: build\WololoKingdoms.zip
